[versions]
minecraft = "1.18.2"
parchment = "2022.11.06"

forge_api = "1.18.2-40.1.69"

fabric_api = "0.58.0+1.18.2"
fabric_loader = "0.14.9"

discord_jda = "5.0.0-beta.9"
discord_webhooks = "0.8.2"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
parchment = { module = "org.parchmentmc.data:parchment-1.18.2", version.ref = "parchment" }

forge_api = { module = "net.minecraftforge:forge", version.ref = "forge_api" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

discord_jda = { module = "net.dv8tion:JDA", version.ref = "discord_jda" }
discord_webhooks = { module = "club.minnced:discord-webhooks", version.ref = "discord_webhooks" }